/* ================================================================
   name.js — 历代诗人数据（纯 JS，不依赖 JSON / fetch）
   直接编辑此文件即可新增/修改诗人数据
=============================================================== */
window.POET_DATA = {
  "dynasties": [
    { "id": "all",     "name": "全部",       "years": "" },
    { "id": "xianqin", "name": "先秦",       "years": "约前11世纪—前221" },
    { "id": "han",     "name": "两汉",       "years": "前202—220" },
    { "id": "weijin",  "name": "魏晋南北朝", "years": "220—589" },
    { "id": "tang",    "name": "唐",         "years": "618—907" },
    { "id": "wudai",   "name": "五代十国",   "years": "907—960" },
    { "id": "song",    "name": "宋",         "years": "960—1279" },
    { "id": "jin",     "name": "金",         "years": "1115—1234" },
    { "id": "yuan",    "name": "元",         "years": "1271—1368" },
    { "id": "ming",    "name": "明",         "years": "1368—1644" },
    { "id": "qing",    "name": "清",         "years": "1644—1912" }
  ],
  "poets": [
    { "dynasty": "xianqin", "name": "屈原" },
    { "dynasty": "xianqin", "name": "宋玉" },
    { "dynasty": "xianqin", "name": "荆轲" },
    { "dynasty": "xianqin", "name": "许穆夫人" },

    { "dynasty": "han", "name": "刘邦" },
    { "dynasty": "han", "name": "刘彻" },
    { "dynasty": "han", "name": "张衡" },
    { "dynasty": "han", "name": "辛延年" },
    { "dynasty": "han", "name": "司马相如" },
    { "dynasty": "han", "name": "贾谊" },
    { "dynasty": "han", "name": "班婕妤" },
    { "dynasty": "han", "name": "蔡琰" },
    { "dynasty": "han", "name": "曹操" },
    { "dynasty": "han", "name": "孔融" },
    { "dynasty": "han", "name": "祢衡" },

    { "dynasty": "weijin", "name": "曹丕" },
    { "dynasty": "weijin", "name": "曹植" },
    { "dynasty": "weijin", "name": "王粲" },
    { "dynasty": "weijin", "name": "陈琳" },
    { "dynasty": "weijin", "name": "刘桢" },
    { "dynasty": "weijin", "name": "嵇康" },
    { "dynasty": "weijin", "name": "阮籍" },
    { "dynasty": "weijin", "name": "陶渊明" },
    { "dynasty": "weijin", "name": "谢灵运" },
    { "dynasty": "weijin", "name": "鲍照" },
    { "dynasty": "weijin", "name": "谢朓" },
    { "dynasty": "weijin", "name": "庾信" },

    { "dynasty": "tang", "name": "王勃" },
    { "dynasty": "tang", "name": "杨炯" },
    { "dynasty": "tang", "name": "卢照邻" },
    { "dynasty": "tang", "name": "骆宾王" },
    { "dynasty": "tang", "name": "陈子昂" },
    { "dynasty": "tang", "name": "孟浩然" },
    { "dynasty": "tang", "name": "王维" },
    { "dynasty": "tang", "name": "李白" },
    { "dynasty": "tang", "name": "杜甫" },
    { "dynasty": "tang", "name": "高适" },
    { "dynasty": "tang", "name": "岑参" },
    { "dynasty": "tang", "name": "王昌龄" },
    { "dynasty": "tang", "name": "王之涣" },
    { "dynasty": "tang", "name": "贺知章" },
    { "dynasty": "tang", "name": "刘长卿" },
    { "dynasty": "tang", "name": "韦应物" },
    { "dynasty": "tang", "name": "韩愈" },
    { "dynasty": "tang", "name": "柳宗元" },
    { "dynasty": "tang", "name": "孟郊" },
    { "dynasty": "tang", "name": "贾岛" },
    { "dynasty": "tang", "name": "李贺" },
    { "dynasty": "tang", "name": "白居易" },
    { "dynasty": "tang", "name": "元稹" },
    { "dynasty": "tang", "name": "刘禹锡" },
    { "dynasty": "tang", "name": "李商隐" },
    { "dynasty": "tang", "name": "杜牧" },
    { "dynasty": "tang", "name": "温庭筠" },
    { "dynasty": "tang", "name": "韦庄" },
    { "dynasty": "tang", "name": "罗隐" },

    { "dynasty": "wudai", "name": "李煜" },
    { "dynasty": "wudai", "name": "冯延巳" },
    { "dynasty": "wudai", "name": "李璟" },
    { "dynasty": "wudai", "name": "孙光宪" },
    { "dynasty": "wudai", "name": "和凝" },
    { "dynasty": "wudai", "name": "牛希济" },
    { "dynasty": "wudai", "name": "毛文锡" },
    { "dynasty": "wudai", "name": "欧阳炯" },

    { "dynasty": "song", "name": "潘阆" },
    { "dynasty": "song", "name": "林逋" },
    { "dynasty": "song", "name": "范仲淹" },
    { "dynasty": "song", "name": "晏殊" },
    { "dynasty": "song", "name": "柳永" },
    { "dynasty": "song", "name": "欧阳修" },
    { "dynasty": "song", "name": "王安石" },
    { "dynasty": "song", "name": "苏轼" },
    { "dynasty": "song", "name": "苏辙" },
    { "dynasty": "song", "name": "黄庭坚" },
    { "dynasty": "song", "name": "秦观" },
    { "dynasty": "song", "name": "周邦彦" },
    { "dynasty": "song", "name": "李清照" },
    { "dynasty": "song", "name": "陆游" },
    { "dynasty": "song", "name": "范成大" },
    { "dynasty": "song", "name": "杨万里" },
    { "dynasty": "song", "name": "辛弃疾" },
    { "dynasty": "song", "name": "姜夔" },
    { "dynasty": "song", "name": "文天祥" },

    { "dynasty": "jin", "name": "元好问" },
    { "dynasty": "yuan", "name": "耶律楚材" },
    { "dynasty": "yuan", "name": "刘因" },
    { "dynasty": "yuan", "name": "赵孟頫" },
    { "dynasty": "yuan", "name": "虞集" },
    { "dynasty": "yuan", "name": "萨都剌" },
    { "dynasty": "yuan", "name": "张养浩" },
    { "dynasty": "yuan", "name": "马致远" },

    { "dynasty": "ming", "name": "刘基" },
    { "dynasty": "ming", "name": "高启" },
    { "dynasty": "ming", "name": "唐寅" },
    { "dynasty": "ming", "name": "徐渭" },
    { "dynasty": "ming", "name": "杨慎" },
    { "dynasty": "ming", "name": "汤显祖" },
    { "dynasty": "ming", "name": "袁宏道" },
    { "dynasty": "ming", "name": "陈子龙" },

    { "dynasty": "qing", "name": "纳兰性德" },
    { "dynasty": "qing", "name": "龚自珍" },
    { "dynasty": "qing", "name": "袁枚" },
    { "dynasty": "qing", "name": "郑燮" },
    { "dynasty": "qing", "name": "顾炎武" },
    { "dynasty": "qing", "name": "吴伟业" },
    { "dynasty": "qing", "name": "王士禛" }
  ]
};
